# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csample.proto\x12\x07\x65xample\"%\n\x05Query\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05_type\x18\x02 \x01(\x08\":\n\x06\x41nswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07\x61nswer2\x18\x02 \x01(\t\x12\x0f\n\x07\x61nswer3\x18\x03 \x01(\t24\n\x07\x45xample\x12)\n\x04\x63\x61ll\x12\x0e.example.Query\x1a\x0f.example.Answer\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sample_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERY']._serialized_start=25
  _globals['_QUERY']._serialized_end=62
  _globals['_ANSWER']._serialized_start=64
  _globals['_ANSWER']._serialized_end=122
  _globals['_EXAMPLE']._serialized_start=124
  _globals['_EXAMPLE']._serialized_end=176
# @@protoc_insertion_point(module_scope)
